SVY-17605 New HTTP plugin has major changes\
if there are HTTP/2 problems like the content length wasn't set
or that there are problems like:
javax.net.ssl.SSLHandshakeException: Cipher suite
`TLS_RSA_WITH_AES_256_CBC_SHA256` does not provide adequate security for
HTTP/2

then we should be able to turn or HTTP/2