SVY-16766 null pointer in readTXTFile
java.lang.NullPointerException: Cannot invoke
"String.contains(java.lang.CharSequence)" because "charsetname" is null
   at com.servoy.extensions.plugins.file.FileProvider.readTXTFile(FileProvider.java:1832)
~[?:?]
   at com.servoy.extensions.plugins.file.FileProvider.js_readTXTFile(FileProvider.java:1800)
~[?:?]
   at com.servoy.extensions.plugins.file.FileProvider.js_readTXTFile(FileProvider.java:1777)
~[?:?]